@startuml

title __JOKER's Class Diagram__\n

  namespace com.joker {
    class com.joker.AddOps {
        - addButton : JButton
        - addTitle : JLabel
        - amountField : JTextField
        - amountLabel : JLabel
        - cancelButton : JButton
        - cardField : JTextField
        - cardLabel : JLabel
        - idField : JTextField
        - idLabel : JLabel
        - locComboBox : JComboBox
        - locationLabel : JLabel
        - mainPanel : JPanel
        - nameField : JTextField
        - nameLabel : JLabel
        - payComboBox : JComboBox
        - payLabel : JLabel
        - priceField : JTextField
        - priceLabel : JLabel
        - quantityField : JTextField
        - quantityLabel : JLabel
        - stockField : JTextField
        - stockLabel : JLabel
        - supplierField : JTextField
        - supplierLabel : JLabel
        + AddOps()
        {static} + launchUI()
    }
  }
  

  namespace com.joker {
    class com.joker.DataTypes {
        - ID : String
        - amount : String
        - cardNumber : String
        - location : String
        - name : String
        - paymentType : String[]
        - price : String
        - quantity : String
        - stock : String
        - supplier : String
        + getAmount()
        + getCardNumber()
        + getID()
        + getLocation()
        + getName()
        + getPaymentType()
        + getPrice()
        + getQuantity()
        + getStock()
        + getSupplier()
        + setAmount()
        + setCardNumber()
        + setID()
        + setLocation()
        + setName()
        + setPaymentType()
        + setPrice()
        + setQuantity()
        + setStock()
        + setSupplier()
    }
  }
  

  namespace com.joker {
    class com.joker.DeleteOps {
        - cancelButton : JButton
        - delTitle : JLabel
        - deleteButton : JButton
        - idComboBox : JComboBox
        - mainPanel : JPanel
        + DeleteOps()
        {static} + launchUI()
    }
  }
  

  namespace com.joker {
    class com.joker.EditOps {
        - amountField : JTextField
        - amountLabel : JLabel
        - cancelButton : JButton
        - cardField : JTextField
        - cardLabel : JLabel
        - editButton : JButton
        - editTitle : JLabel
        - idField : JTextField
        - idLabel : JLabel
        - locComboBox : JComboBox
        - locationLabel : JLabel
        - mainPanel : JPanel
        - nameField : JTextField
        - nameLabel : JLabel
        - payComboBox : JComboBox
        - payLabel : JLabel
        - priceField : JTextField
        - priceLabel : JLabel
        - quantityField : JTextField
        - quantityLabel : JLabel
        - recComboBox : JComboBox
        - recordLabel : JLabel
        - stockField : JTextField
        - stockLabel : JLabel
        - supplierField : JTextField
        - supplierLabel : JLabel
        + EditOps()
        {static} + launchUI()
    }
  }
  

  namespace com.joker {
    class com.joker.FileOps {
        - buffer : List<List<String>>
        - csvFile : File
        - fileName : String
        + getBuffer()
        + getCsvFile()
        + readFile()
        + setFileName()
    }
  }
  

  namespace com.joker {
    class com.joker.Inventory {
        {static} - InvFile : FileOps
        - addButton : JButton
        {static} - console : Scanner
        {static} - data : DataTypes
        - datePickerButton : JButton
        - deleteButton : JButton
        - editButton : JButton
        {static} - invArray : ArrayList<DataTypes>
        - invPanel : JPanel
        - invScrollPane : JScrollPane
        - invTable : JTable
        - menuButton : JButton
        - menuLabel : JLabel
        - nextButton : JButton
        - previousButton : JButton
        - refreshButton : JButton
        {static} - row : Object[]
        - saveButton : JButton
        {static} - saved : boolean
        {static} - tableData : DefaultTableModel
        - tablePanel : JPanel
        - textField1 : JTextField
        - toolbar : JPanel
        + Inventory()
        {static} + addData()
        {static} + editData()
        {static} + fetch()
        {static} + inventory()
        {static} + launchUI()
        {static} + main()
        {static} + printTable()
    }
  }
  

  namespace com.joker {
    class com.joker.LaunchScreen {
        - exitButton : JButton
        - launchButton : JButton
        - launchPanel : JPanel
        + LaunchScreen()
        {static} + main()
    }
  }
  

  namespace com.joker {
    class com.joker.Main {
        {static} + main()
    }
  }
  

  namespace com.joker {
    class com.joker.MainMenu {
        - inventoryButton : JButton
        - mainMenuPanel : JPanel
        - reportsButton : JButton
        - salesButton : JButton
        - transactionsButton : JButton
        + MainMenu()
        {static} + launchUI()
    }
  }
  

  namespace com.joker {
    class com.joker.Reports {
    }
  }
  

  namespace com.joker {
    class com.joker.Sales {
        - addButton : JButton
        - datePickerButton : JButton
        - deleteButton : JButton
        - editButton : JButton
        - invScrollPane : JScrollPane
        - invTable : JTable
        - menuButton : JButton
        - menuLabel : JLabel
        - nextButton : JButton
        - previousButton : JButton
        - refreshButton : JButton
        - saveButton : JButton
        - tablePanel : JPanel
        - textField1 : JTextField
        - toolbar : JPanel
    }
  }
  

  namespace com.joker {
    class com.joker.SalesData {
        - ID : String
        - name : String
        - sold : String
        - stock : String
        - supplier : String
        + SalesData()
        + getID()
        + getName()
        + getSold()
        + getStock()
        + getSupplier()
    }
  }
  

  namespace com.joker {
    class com.joker.Transactions {
        - addButton : JButton
        - datePickerButton : JButton
        - deleteButton : JButton
        - editButton : JButton
        - invScrollPane : JScrollPane
        - invTable : JTable
        - menuButton : JButton
        - menuLabel : JLabel
        - nextButton : JButton
        - previousButton : JButton
        - refreshButton : JButton
        - saveButton : JButton
        - tablePanel : JPanel
        - textField1 : JTextField
        - toolbar : JPanel
    }
  }
  

  com.joker.AddOps -up-|> javax.swing.JFrame
  com.joker.DeleteOps -up-|> javax.swing.JFrame
  com.joker.EditOps -up-|> javax.swing.JFrame
  com.joker.Inventory -up-|> javax.swing.JFrame
  com.joker.LaunchScreen -up-|> javax.swing.JFrame
  com.joker.MainMenu -up-|> javax.swing.JFrame


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
